sudo: true
language: ruby
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t gbrody/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gbrody/docker-react npm run test

