sudo: true
language: ruby
os: linux
dist: xenial

services:
  - docker

before_install:
  - docker build -t gbrody/nginx -f Dockerfile .

script:
  - docker run -d --name webserver -p 127.0.0.1:80:80 gbrody/nginx

